/**
 * Main entry point for Scarab JAR.
 *
 * Scarab is a library for SAT-based constraint programming.
 * This main class provides usage instructions and examples.
 */
object ScarabMain {

  def main(args: Array[String]): Unit = {
    if (args.length > 0 && args(0) == "--test") {
      println("Running CaDiCaL integration tests...")
      CaDiCaLTest.main(Array.empty)
      return
    }

    println()
    println("=" * 70)
    println("  Scarab: SAT-based Constraint Programming Library")
    println("  Version: 1.9.7-SNAPSHOT")
    println("=" * 70)
    println()
    println("Scarab is a Scala library for solving constraint satisfaction problems")
    println("using SAT solvers. It provides:")
    println()
    println("  • High-level DSL for CSP modeling")
    println("  • Multiple SAT solver backends (Sat4j, CaDiCaL)")
    println("  • Order encoding for integer variables")
    println("  • Support for cardinality and pseudo-boolean constraints")
    println()
    println("-" * 70)
    println("USAGE AS A LIBRARY")
    println("-" * 70)
    println()
    println("1. Add scarab.jar to your classpath:")
    println("   scala -cp scarab.jar YourProgram.scala")
    println()
    println("2. In your Scala code:")
    println()
    println("   import jp.kobe_u.scarab._")
    println("   import jp.kobe_u.scarab.dsl._")
    println()
    println("   // Define variables")
    println("   int('x, 1, 10)")
    println("   int('y, 1, 10)")
    println()
    println("   // Add constraints")
    println("   add('x + 'y === 15)")
    println("   add('x > 'y)")
    println()
    println("   // Solve")
    println("   if (find) {")
    println("     println(s\"x = ${solution.intMap('x)}\")")
    println("     println(s\"y = ${solution.intMap('y)}\")")
    println("   }")
    println()
    println("-" * 70)
    println("USING CaDiCaL SOLVER")
    println("-" * 70)
    println()
    println("Scarab now supports CaDiCaL, a state-of-the-art SAT solver.")
    println()
    println("To use CaDiCaL instead of the default Sat4j:")
    println()
    println("   use(new CaDiCaLSolver())")
    println()
    println("Note: Requires libcadical.so to be installed in:")
    println("  • ~/.local/lib/")
    println("  • /usr/local/lib/")
    println("  • Or set LD_LIBRARY_PATH")
    println()
    println("-" * 70)
    println("SOLVERS COMPARISON")
    println("-" * 70)
    println()
    println("  Sat4j (default):")
    println("    • Pure Java implementation")
    println("    • Native pseudo-boolean constraint support")
    println("    • UNSAT core extraction")
    println("    • No external dependencies")
    println()
    println("  CaDiCaL (optional):")
    println("    • Native C++ implementation")
    println("    • Faster on many instances")
    println("    • Lower memory usage")
    println("    • Requires native library installation")
    println()
    println("-" * 70)
    println("EXAMPLES")
    println("-" * 70)
    println()
    println("Run built-in examples:")
    println("  • N-Queens problem:    scala -cp scarab.jar examples/NQueens.scala")
    println("  • Graph coloring:      scala -cp scarab.jar examples/GraphColoring.scala")
    println("  • Magic square:        See HowToWriteProblems object")
    println()
    println("Run CaDiCaL tests:")
    println("  java -jar scarab.jar --test")
    println()
    println("-" * 70)
    println("SBT/MAVEN USAGE")
    println("-" * 70)
    println()
    println("build.sbt:")
    println("  libraryDependencies += \"jp.kobe_u.scarab\" %% \"scarab\" % \"1.9.7-SNAPSHOT\"")
    println()
    println("Or use as unmanaged dependency:")
    println("  • Copy scarab.jar to lib/ directory in your project")
    println("  • sbt will automatically add it to classpath")
    println()
    println("-" * 70)
    println("DOCUMENTATION")
    println("-" * 70)
    println()
    println("  • Project page: http://tsoh.org/scarab/")
    println("  • GitHub:       https://github.com/TakehideSoh/Scarab")
    println("  • CaDiCaL docs: See CADICAL_README.md")
    println()
    println("-" * 70)
    println("AVAILABLE SAT SOLVERS")
    println("-" * 70)
    println()
    println("Default (Sat4j):")
    println("  use(new Sat4j())              // Default solver")
    println("  use(new Sat4j(\"glucose\"))     // Glucose variant")
    println("  use(new Sat4j(\"xplain\"))      // With UNSAT core")
    println()
    println("CaDiCaL:")
    println("  use(new CaDiCaLSolver())      // Native CaDiCaL solver")
    println()
    println("External:")
    println("  use(new ExtSatSolver(\"./solver\"))  // External DIMACS solver")
    println()
    println("-" * 70)
    println("QUICK START")
    println("-" * 70)
    println()
    println("1. Create a file 'example.scala':")
    println()
    println("   import jp.kobe_u.scarab.dsl._")
    println()
    println("   object Example extends App {")
    println("     int('x, 1, 5)")
    println("     int('y, 1, 5)")
    println("     add('x + 'y === 7)")
    println("     if (find) println(solution)")
    println("   }")
    println()
    println("2. Run it:")
    println("   scala -cp scarab.jar example.scala")
    println()
    println("=" * 70)
    println()
    println("For more information, visit: http://tsoh.org/scarab/")
    println()
  }
}
